export const COUNTRY_NAMES: Record<string, string> = {
  AR: 'Argentina',
  AU: 'Australia',
  BR: 'Brazil',
  CA: 'Canada',
  CN: 'China',
  FR: 'France',
  DE: 'Germany',
  IN: 'India',
  ID: 'Indonesia',
  IT: 'Italy',
  JP: 'Japan',
  MX: 'Mexico',
  RU: 'Russia',
  SA: 'Saudi Arabia',
  ZA: 'South Africa',
  KR: 'South Korea',
  TR: 'Turkey',
  GB: 'United Kingdom',
  US: 'United States',
  ES: 'Spain',
  AE: 'UAE',
  SG: 'Singapore',
  NG: 'Nigeria',
  DEFAULT: 'Global (112)',
};

export const COUNTRY_FLAGS: Record<string, string> = {
  AR: '🇦🇷', AU: '🇦🇺', BR: '🇧🇷', CA: '🇨🇦', CN: '🇨🇳',
  FR: '🇫🇷', DE: '🇩🇪', IN: '🇮🇳', ID: '🇮🇩', IT: '🇮🇹',
  JP: '🇯🇵', MX: '🇲🇽', RU: '🇷🇺', SA: '🇸🇦', ZA: '🇿🇦',
  KR: '🇰🇷', TR: '🇹🇷', GB: '🇬🇧', US: '🇺🇸', ES: '🇪🇸',
  AE: '🇦🇪', SG: '🇸🇬', NG: '🇳🇬', DEFAULT: '🌐',
};
